// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsboucrtgxrpnmebrrph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzYm91Y3J0Z3hycG5tZWJycnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDI4OTQsImV4cCI6MjA3NjE3ODg5NH0.kf6LeXstGQXeTxZI00PaE4EVsEiWaxVcAtipYlWXibE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});