// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmqtvnurwoispusqlsgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcXR2bnVyd29pc3B1c3Fsc2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDMzNjYsImV4cCI6MjA3MTM3OTM2Nn0.HZkqtcr-XC0k2QwTtOjvzjemGVYpcfoVcB9zVP09ab4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});